### ISSUE TITLE
项目还有在维护吗

### ISSUE THREAD

**Issue by lazyabp** [dotnetcore/Util#100]
好长时间没更新了，还有在维护吗？

**Comment by UtilCore** [comment]
util 5.0最新版本正在开发中,基于.net 5,大部分代码完全重写,更新还需要几个月,目前正在开发UI部分,还是基于ng zorro,这次会覆盖ng zorro全部组件,请耐心等待

**Comment by yangjie955330** [comment]
预计好久，求更新
