### ISSUE TITLE
Util.Webs.Clients下 GET请求报错

### ISSUE THREAD

**Issue by yusliao** [dotnetcore/Util#12]
```cs
private HttpRequestMessage CreateRequestMessage() 
{
    var message = new HttpRequestMessage {
        Method = _httpMethod,
        RequestUri = new Uri( _url ),
        Content = CreateHttpContent() //GET请求不能给content赋值 
    };
    foreach( var header in _headers )
        message.Headers.Add( header.Key, header.Value );
    return message;
}
```

**Comment by UtilCore** [comment]
能发下你的调用代码吗

**Comment by yusliao** [comment]
哦，在.net core中没问题。我在.net Framework下报的错误~ 抱歉~
 public static async Task<(bool existed, string resourceId)> FindResource(string resourceName)
        {
            try
            {
                //验证资源是否存在
                var filedata = File.ReadAllBytes(resourceName);
                var name = Util.Helpers.Encrypt.Md5By32(filedata);
                var t = await new Util.Webs.Clients.WebClient().Get("http://192.168.4.24:8090/api/File/IsExist?fileCode=5dc0943efe0df1817ebd58473e1c3408.png")
                    .ContentType(Util.Webs.Clients.HttpContentType.Json)
                    .ResultAsync();
                var obj = Util.Helpers.Json.ToObject<webapiResult>(t);
                if (obj.isExist)
                    return (true, name);
                else
                    return (false, name);
            }
            catch (Exception)
            {
                throw;
            }
        }

**Comment by UtilCore** [comment]
应该这样调用:
`var obj = Util.Helpers.Web.Client()
                 .Get( "http://192.168.4.24:8090/api/File/IsExist")
                 .Data( "fileCode", "5dc0943efe0df1817ebd58473e1c3408.png" )
                .ResultFromJson<webapiResult>();`
