### ISSUE TITLE
issue of extension function MapTo

### ISSUE THREAD

**Issue by maverickljw** [dotnetcore/Util#14]
private static TDestination MapTo<TDestination>( object source, TDestination destination )
这个方法里面会判断源对象和目标对象是否配置了Map，如果没有配置的话，则自动CreateMap。
针对EF的代理对象，尽管系统已经配置了Entity和Dto的Map，但是在上面方法里获取不到代理对象和Dto的Map配置，然后重新配置Map，导致自定义的Map配置条件失效了。

**Comment by UtilCore** [comment]
@maverickljw 你好，代理对象的问题确实非常麻烦，我没有找到好的办法来判断是否是代理，有一种丑陋的办法是查找对象名称是否包含特定关键字。你能提供EF代理对象的样例名称吗，多给几个。

**Comment by maverickljw** [comment]
代理对象Type的full name举例：
u.GetType().FullName
"System.Data.Entity.DynamicProxies.User_8F682D0B0A658523C6F71898F12F31FA72950F1CAC8108C028176279FD8E50BE"

我看了一下，如果是代理对象的话，其BaseType指向了原本的对象，如下：
u.GetType().BaseType
{Name = "User" FullName = "Mavercloud.OnlinePublication.DataEntities.Entities.User"}

应该可以根据这个来：）

**Comment by UtilCore** [comment]
@maverickljw 请问你是用的EF还是EF  Core?

**Comment by maverickljw** [comment]
EF

**Comment by UtilCore** [comment]
@maverickljw 我这用的EF CORE，没这问题呢，你如果修复了这个问题，提交一个pr吧

**Comment by maverickljw** [comment]
抱歉，暂时还无法提交pr，先把我改的地方标识一下吧（比较丑陋的方法，暂时符合我这边的情况）：

private static Type GetType( object obj ) {
            var type = obj.GetType();
            if ((obj is System.Collections.IEnumerable) == false)
                **if (type.FullName.StartsWith("System.Data.Entity.DynamicProxies"))
                {
                    return type.BaseType;
                }
                else
                {
                    return type;
                }**
            if( type.IsArray )
                return type.GetElementType();
            var genericArgumentsTypes = type.GetTypeInfo().GetGenericArguments();
            if( genericArgumentsTypes == null || genericArgumentsTypes.Length == 0 )
                throw new ArgumentException( "泛型类型参数不能为空" );
            return genericArgumentsTypes[0];
        }
