### ISSUE TITLE
Cannot consume scoped service 'DotNetCore.CAP.ICapPublisher' from singleton 。

### ISSUE THREAD

**Issue by Basil1991** [dotnetcore/Util#20]
InvalidOperationException: Cannot consume scoped service 'DotNetCore.CAP.ICapPublisher' from singleton 'Util.Event.Messages.IMessageEventBus'.

services.AddSingleton<IMessageEventBus, MessageEventBus>();
services.AddSingleton<IEventBus, EventBus>();

需要把 AddSingleton 改成 “AddScoped”才不会报错。
是否有其他设置可以把ICapPublisher改为Singleton？

**Comment by UtilCore** [comment]
目前CAP尚未封装到UTIL，上次封装了一半停下了，有空再继续
