### ISSUE TITLE
AutoMap改进

### ISSUE THREAD

**Issue by 853495865** [dotnetcore/Util#27]
这是现在的代码
![image](https://user-images.githubusercontent.com/10707284/41341929-8f2d80e6-6f2d-11e8-8d7e-ceebbf57e7e3.png)
我觉得可以改成
![image](https://user-images.githubusercontent.com/10707284/41341969-ab2e6698-6f2d-11e8-8291-d86903e497e1.png)
先尝试进行map，如果失败了，才进行下面的动作

**Comment by UtilCore** [comment]
这里的try catch比较复杂，因为automapper在很多情况下会抛出异常，代码结构暂时这样，有单元测试保障基本的正确性。
