### ISSUE TITLE
mapper 遇到未注册过的Type时，会initMaps,但原有类型会丢失CustomMapper

### ISSUE THREAD

**Issue by kaanid** [dotnetcore/Util#41]
initMaps,但原有类型会丢失，自定义设置CustomMapper
item.CustomMapper!=null
重新init
item.CustomMapper==null

**Comment by UtilCore** [comment]
请提供代码示例让我重现BUG

**Comment by kaanid** [comment]
代码在这里，https://github.com/kaanid/custommapper
请看一下。谢谢

**Comment by kaanid** [comment]
棒
