### ISSUE TITLE
请问IUnitOfWork是个什么概念？

### ISSUE THREAD

**Issue by AdamvvYau** [dotnetcore/Util#44]
很多地方看到有IUnitOfWork，这个是什么概念？用来分区？
另外，
    [Model( "model" )]
    public class RoleDto 
Dto类属性Model又是用来标识什么的呢？会在哪里有效果？
谢谢！

**Comment by UtilCore** [comment]
IUnitOfWork是工作单元，工作单元的概念出自《企业应用架构模式》，它用来记录将对象进行数据库操作时所产生的变化，EF Core的DbContext实现了这个概念，我抽象接口只是为了增加一点扩展性，万一以后要切换其它ORM时有用。

**Comment by UtilCore** [comment]
Model属性是在我封装的Angular + Material这套UI上用的，用来指定ngModel绑定的模型名称，你不需要用到这个东西。

**Comment by AdamvvYau** [comment]
谢谢解答！！
