### ISSUE TITLE
在Util.Datas.Ef.Core.UnitOfWorkBase的OnModelCreating方法

### ISSUE THREAD

**Issue by AdamvvYau** [dotnetcore/Util#45]
在Util.Datas.Ef.Core.UnitOfWorkBase中
在每次new IUnitOfWork的实例都需要调用下面方法。如果一个库有2000个表，就有两2000个IMap。每次都要重新Create这么多个Model?有没有可能只载入一次呢？或者为什么设计为每次都要重新CreateAll?
        /// <summary>
        /// 配置映射
        /// </summary>
        protected override void OnModelCreating( ModelBuilder modelBuilder ) {
            foreach( IMap mapper in GetMaps() )
                mapper.Map( modelBuilder );
        }

**Comment by UtilCore** [comment]
因为每个请求都要创建新的工作单元，在OnModelCreating配置映射，一次性配置好映射确实很好，但在哪里做呢？

**Comment by UtilCore** [comment]
想了下，最多能搞点缓存，配置是必须的，缓存查找到的IMap列表

**Comment by AdamvvYau** [comment]
> 想了下，最多能搞点缓存，配置是必须的，缓存查找到的IMap列表

我觉得这个方法可以

**Comment by UtilCore** [comment]
根据你的建议，已经更新，请测试一下
