### ISSUE TITLE
ISqlQuery的应用场景是什么？

### ISSUE THREAD

**Issue by 32167t** [dotnetcore/Util#47]
最近的Commit都是有关于SqlQuery的实现部分。
目前来看Domain层是不可能使用，只需要关注IRepository就行。
因为有Ef的存在，执行Sql语句EF也能够做到，那引入Dapper的意义又不存在了。
如果是想使用Dapper，那么常规的做法应该是再封装一套Store以及关于IDbConnection的Iqueryable的实现。目前看因为sql语句生成依赖于Ef的实体映射也不是太像。
想询问一下关于ISqlQuery这个类型的真实应用场景

**Comment by UtilCore** [comment]
IRepository仓储的概念是聚合的集合，这个集合是模拟的，它的价值是帮助开发业务逻辑时执行数据操作，既有添加修改删除，也有查找方法，基类上定义了一些通用的常规方法，但对于业务并不友好，当你要执行单元测试时，在具体仓储定义特定查询方法会方便单元测试模拟，同时也提供了一个聚合查询封装的地方。
EF虽然可以执行查询，但不论是LINQ方法还是LINQ语句对于复杂的查询都是无能为力的，复杂的查询必须使用SQL语句，用EF只应该执行简单的查询工作。
EF可以执行SQL，但相当笨重，使用Dapper配合是一个不错的选择，Dapper提供了参数化以及简单映射能力，你只要提供SQL语句即可。
但是复杂的SQL查询语句本身写起来也有很多问题，比如不同的数据库有自己的转义符，Sql Server使用[]，PgSql使用""，MySql使用``，对于像PGSQL这样的数据库，如果表名或列名有大写字母，那么必须加上转义字符。另外查询条件你需要判断值是否是空值，空值不应该添加条件，另外参数化也需要额外的工作，哪怕你使用了Dapper。
另外，习惯使用Linq的朋友喜欢用强类型的Lambda表达式来设置列名或查询条件。
但你使用纯SQL字符串时，调试也很麻烦，因为你的SQL已经参数化，你必须替换成实际的值才可以执行查询。
Util捕获了上述问题，并企图解决它们，实现了ISqlQuery，但随着不同的人群，可能不一定喜欢它。
ISqlQuery的一个最大特点是允许Lambda操作和字符串操作同时使用，你可以在任何位置使用SQL字符串，也可以在某些位置使用Lambda表达式。
ISqlQuery拥有开发日志，会输出带参数化的SQL，也会输出用实际值替换过的SQL，方便调试。
最后，ISqlQuery会读取EF元数据，如果你的Lambda表达式的属性名和数据库的列名不同，就能占一点便宜。
开发IQueryable的Dapper提供程序无法解决复杂查询的问题，因为纯强类型的东西很难表达出你想要的SQL。
ISqlQuery生成的SQL是完全可控的，这只是一个高级版的SqlHelper，不是什么ORM。
