### ISSUE TITLE
sql where 表达式树里求值的疑问

### ISSUE THREAD

**Issue by kaanid** [dotnetcore/Util#48]
sql where 表达式树里求值的疑问
如：
```
[Fact]
public void TestWhere_17_1()
{
        
        //执行
       _clause.Where<Sample>(t => t.Created>Datetime.Now.AddDays(-7));

 }
```

这种情况，如何处理？

提倡提前计算好，再进行表达式树的方法。

是否可以支持这种方式：

可通过下面这样方法来求值 
```
Expression.Lambda(expression).Compile().DynamicInvoke();
```

**Comment by UtilCore** [comment]
一般情况下提前进行计算是推荐的方法。
lambda表达式中如果要支持特定的语法，必须进行特定的测试，另外可能会把某些方法调用转换成数据库内部函数，目前SqlQuery还处于基础实现阶段，高级特性尚未考虑。
使用DynamicInvoke可能会出现非预期的结果，暂时不会考虑这个方案。
