### ISSUE TITLE
Angular.Material 无法安装node-sass模块

### ISSUE THREAD

**Issue by Lyjliuyujun** [dotnetcore/Util#56]
Angular.Material 无法安装node-sass模块

**Comment by UtilCore** [comment]
看我这篇
https://www.cnblogs.com/xiadao521/p/Util-Introduction-2.html

另外我现在正在封装ng zorro组件，不需要node-sass，可以关注

**Comment by Lyjliuyujun** [comment]
确实，之前了解过ng  zorro样式什么的各方面看着比较清淡很舒适




| |
刘昱均
邮箱：13269415864@163.com
|

签名由 网易邮箱大师 定制

在2019年03月26日 12:26，何镇汐 写道：

Closed #56.
