### ISSUE TITLE
ISqlQuery 实列，被多个线程调用时疑问

### ISSUE THREAD

**Issue by kaanid** [dotnetcore/Util#75]
一个类里，有2个方法使用ISqlQuery，ISqlQuery通过构造方法注入，并是单例。
在多钱程的情况下，
2个方法，存在同时被调用的可能。
此时，ISqlQuery 要如何来使用？

发现ISqlBuilder存在一个New方法
而ISqlQuery并没有New方法

请问这样设计是基于什么样的考虑？
感谢。

**Comment by UtilCore** [comment]
ISqlQuery并不是单例的，不能把它配置为单例来用。
设计SqlQuery的动机是用来配合EF解决复杂查询的问题，默认情况下，会将EF Core的DbContext注入到SqlQuery中，用来提供数据库连接和元数据映射，所以不能配置成单例，当然SqlQuery并不是跟EF Core完全耦合的，在不使用EF的情况下同样可以使用，只需要实现几个接口即可。
所以不必担心多线程场景的问题，多个线程访问的是多个类实例，不会互相影响。
如果确实碰到多个线程操作同一个SqlQuery实例的情况，也是有办法解决，虽然没有提供NewQuery方法，但有一个Clone，用来复制当前SqlQuery实例。
最后，SqlQuery实例在一个方法执行完会自动清理之前的状态，在另一个方法中执行是没有问题的，在必要的时候通过Clone来复制当前SqlQuery实例。
希望对你有帮助。

**Comment by kaanid** [comment]
了解了。
准备单独出来使用，增加New接口。
感谢
