### ISSUE TITLE
Update from NLog BETA to NLog 4.5.11 or newer

### ISSUE THREAD

**Issue by snakefoot** [dotnetcore/Util#76]
https://github.com/dotnetcore/Util/blob/87d62687f0da8d91c35d37c689dd8cdf814e6fd7/src/Util.Logs/03-Util.Logs.csproj#L39

Latest official package: https://www.nuget.org/packages/NLog

See also [NLog 4.5 is near! (and no NLog 5)](https://nlog-project.org/2017/12/20/nlog-4-5-is-near.html)

**Comment by UtilCore** [comment]
好的，一会更新到nlog 4.6.6
