### ISSUE TITLE
继承CrudServiceBase使用update方法，会更新创建人和创建时间为null

### ISSUE THREAD

**Issue by ToNewDay** [dotnetcore/Util#79]

**Comment by ToNewDay** [comment]
`        public virtual void Update( TEntity entity ) {
            if( entity == null )
                throw new ArgumentNullException( nameof( entity ) );
            UnitOfWork.Entry( entity ).State = EntityState.Detached;
            var old = Find( entity.Id );
            var oldEntry = UnitOfWork.Entry( old );
            if ( !( entity is IVersion version ) ) {
                oldEntry.CurrentValues.SetValues( entity );
                return;
            }
            oldEntry.State = EntityState.Detached;
            oldEntry.CurrentValues[nameof( version.Version )] = version.Version;
            oldEntry = UnitOfWork.Attach( old );
            oldEntry.CurrentValues.SetValues( entity );
        }`
当前修改Util.Datas.Ef.Core 的Update方法，给entity的创建人创建时间赋值。请问是否有更合适的做法

**Comment by UtilCore** [comment]
能提供更详细的重现步骤吗，未测试出这样的结果

**Comment by ToNewDay** [comment]
```
 public class AssetAccount : AggregateRoot<AssetAccount>, IDelete, IAudited
    {
        public AssetAccount() : this(Guid.NewGuid())
        {
        }

        public AssetAccount(Guid id) : base(id)
        {
        }

        public string AccountName { get; set; }

        public decimal FreeAmount { get; set; }

        public string AccountNo { get; set; }

        public bool IsDeleted { get; set; }

        public DateTime? CreationTime { get; set; }

        public Guid? CreatorId { get; set; }

        public DateTime? LastModificationTime { get; set; }

        public Guid? LastModifierId { get; set; }
    }
```

```
 public class AssetAccountDto : DtoBase
    {
        public string AccountName { get; set; }

        public decimal FreeAmount { get; set; }

        public string AccountNo { get; set; }

        public Byte[] Version { get; set; }

    }
```
以上是domain model类和dto类。dto类更新到entity时会执行以下方法（Util.Datas\Ef\Core\StoreBase.cs）
```
        /// <summary>
        /// 修改实体
        /// </summary>
        /// <param name="entity">实体</param>
        public virtual void Update( TEntity entity ) {
            if( entity == null )
                throw new ArgumentNullException( nameof( entity ) );
            UnitOfWork.Entry( entity ).State = EntityState.Detached;
            var old = Find( entity.Id );
            var oldEntry = UnitOfWork.Entry( old );
            if ( !( entity is IVersion version ) ) {
                oldEntry.CurrentValues.SetValues( entity );
                return;
            }
            oldEntry.State = EntityState.Detached;
            oldEntry.CurrentValues[nameof( version.Version )] = version.Version;
            oldEntry = UnitOfWork.Attach( old );
            oldEntry.CurrentValues.SetValues( entity );
        }
```
执行上面的更新在oldEntry.CurrentValues.SetValues( entity )步骤，因为entity的创建人和创建时间是null。因此会更新oldEntry的创建时间创建人为null。后面的拦截器上会添加修改人和修改时间，但是对于创建人创建时间的处理就到这里为止。目前我是修改了这段update方法。
感觉应该是我使用方式的问题，还请告知正确的代码实践。
因为使用的react+ant desing pro做的前端，所以还没有研究Util的一整套处理方式，不知道答案是否在其中。

**Comment by UtilCore** [comment]
这里的主要问题是DTO的定义存在问题,理论上PUT应该传回这次修改的所有数据,如果你只传回部分数据,需要先从仓储 find 回这个对象,然后再把 DTO 的部分属性MapTo映射上去,这样保证对象上的数据完整,否则会丢失数据.

**Comment by ToNewDay** [comment]
对于创建时间，创建人栏位，每个业务的service层都从仓储find回来给entity赋值，似有不妥。
