### ISSUE TITLE
有集成第三方支付的计划吗？

### ISSUE THREAD

**Issue by Varorbc** [dotnetcore/Util#8]
有集成第三方支付的计划吗？

**Comment by seayxu** [comment]
这个会有的

**Comment by UtilCore** [comment]
@Varorbc 之前本来想集成封装支付宝SDK的，但它没有.net core版本，我本来想移植下，但里面有很多算法相关的东西，而且还引用了一个操作json和xml的第三方类库，这个类库也没有支持.net core，暂时不考虑。看官方会不会提供一个.net core的版本，或其他人愿意迁移过来。

**Comment by Varorbc** [comment]
@UtilCore 需要移除支付以外的代码吗？我试试看
