### ISSUE TITLE
Web.GetParam("aaa")

### ISSUE THREAD

**Issue by fmpfmp** [dotnetcore/Util#82]
没传aaa这个参数，会报异常：
`System.InvalidOperationException: Incorrect Content-Type: `

**Comment by jianxuanbing** [comment]
> 没传aaa这个参数，会报异常：
> `System.InvalidOperationException: Incorrect Content-Type: `

这个是支付模块的提示?

**Comment by UtilCore** [comment]
没传参数返回的是空字符串
