### ISSUE TITLE
partial class 建议

### ISSUE THREAD

**Issue by fmpfmp** [dotnetcore/Util#83]
提个建议：建议把一些class 加上 partial， 方便扩展

比如Helpers里的帮助类，用partial class扩展几个自己要用的方法，就可以统一调用了

**Comment by jianxuanbing** [comment]
需要扩展什么方法呢

**Comment by jianxuanbing** [comment]
> 提个建议：建议把一些class 加上 partial， 方便扩展
> 
> 比如Helpers里的帮助类，用partial class扩展几个自己要用的方法，就可以统一调用了

那些方法呢

**Comment by WuMianRen** [comment]
对于框架 你只需给出扩展  至于添加什么方法那是应用框架的人自己想添加什么就添加什么
类似于MVC 控制器工厂之类的   只需要开放扩展  使用的人随意扩展控制器工厂即可  
个人建议

**Comment by UtilCore** [comment]
常用基类和helper已经添加，还有需要请留言
