### ISSUE TITLE
报 Cannot find module './wwwroot/dist/util-manifest.json' 通常是因为哪个包没有还原好?

### ISSUE THREAD

**Issue by AmazingCoder2018** [dotnetcore/Util#86]
我下载了之后,等待后台还原各种包,当我发现左下角提示没有后台任务时,就把"Util.Samples.Angular.AntDesign"设为启动项目,然后F5了. 然后 在Startup.cs里的
`app.UseWebpackDevMiddleware( new WebpackDevMiddlewareOptions {
                HotModuleReplacement = true
            } );` 就报上述错误了,这个大概是什么引起的?

**Comment by jianxuanbing** [comment]
因为你没有进行 npm run  xxxx。
你看看这篇文章：https://www.cnblogs.com/xiadao521/p/Util-Introduction-3.html

**Comment by UtilCore** [comment]
不要用VS还原包

**Comment by AmazingCoder2018** [comment]
没有用过npm和webpack.请问怎么还原这些前端包？我电脑上装了node.js 10,还把npm的repository设置成了淘宝的。然后能编译通过了。但是不能启动调试。------------------ 原始邮件 ------------------
发件人: "何镇汐"<notifications@github.com>
发送时间: 2019年12月13日(星期五) 下午4:33
收件人: "dotnetcore/Util"<Util@noreply.github.com>;
抄送: "李立飞"<1933559183@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dotnetcore/Util] 报 Cannot find module './wwwroot/dist/util-manifest.json' 通常是因为哪个包没有还原好? (#86)



不要用VS还原包
 
&mdash;

**Comment by AmazingCoder2018** [comment]
谢谢.我阅读了前3篇文章,受益匪浅.一遍读,心里一遍澎湃. 然后按照第二篇文章介绍的命令,执行后. 就可以F5跑起来了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jian玄冰"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 中午11:12
收件人: "dotnetcore/Util"<Util@noreply.github.com&gt;; 
抄送: ""<1933559183@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dotnetcore/Util] 报 Cannot find module &#39;./wwwroot/dist/util-manifest.json&#39; 通常是因为哪个包没有还原好? (#86)




因为你没有进行 npm run  xxxx。
 你看看这篇文章：https://www.cnblogs.com/xiadao521/p/Util-Introduction-3.html
