### ISSUE TITLE
框架能否出一个框架设计说明文档同步更新？

### ISSUE THREAD

**Issue by yujiajunbmj** [dotnetcore/Util#96]
你好：
       我们已将此框架运用到实际项目中，有一些设计思路比较困惑看起来比较吃力，能否将框架中用到的技术、设计思路、场景等编写成一个文档进行同步更新，便于大家更好的理解整个框架，将整个框架运用到更加完整

**Comment by peiwen-zhang** [comment]
支持一下  同运用到项目当中  我现在搞不清一些用法  很多时候都是自己读源码学习怎么使用

**Comment by peiwen-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
最近在忙有事电联！
